name: Cypress Tests

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run dev
        env:
          VITE_SVELTE_APP_SUPABASE_URL: ${{ secrets.VITE_SVELTE_APP_SUPABASE_URL }}
          VITE_SVELTE_APP_SUPABASE_ANON_KEY: ${{ secrets.VITE_SVELTE_APP_SUPABASE_ANON_KEY }}
